const express = require('express');
const path = require('path');
const logger = require('morgan');
const fs = require('mz/fs');
const {exec} = require('child_process');

const APP_PATH = '/angularJS';

let api = {};
api.authenticate = require('./express/api/authenticate');
api.users = require('./express/api/users');


const app = express();
app.use(express.static(path.join(__dirname, 'public')));
app.set('views', __dirname + APP_PATH);
app.set('view engine', 'jade');

app.use(logger('dev'));

/**
 * Render main page with style generated by passed params and provide jade all FA icons array and placehold images for background
 */

app.use('/api/authenticate', api.authenticate);
app.use('/api/users', api.users);

app.get('/', (req, res) => {
    res.render('index');
}, (err) => {
    res.status(500).json(err);
});

app.get('/views/:template', (req, res) => {
    const template = req.params.template && fs.existsSync(path.join(__dirname, APP_PATH + '/jade/' + req.params.template + '.jade')) ? req.params.template : null;
    if (template)  {
        fs.readFile(path.join(__dirname, APP_PATH + '/assets/i18n/en/data.json'), 'utf8').then(contents => {
            try {
                res.render('jade/' + template, JSON.parse(contents));
            } catch(e) {
                res.status(500).json(e);
            }
        }).catch(err => {
            res.status(500).json(err);
        });
    } else {
        res.status(404).json({error: 'Template not found'});
    }
}, (err) => {
    res.status(500).json(err);
});

app.listen(3000);
